version: "3.1"

services:
  bot:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - .:/app
      - .:/opt/gcloud
    depends_on:
      - mongo
      - serving
    env_file:
      - ./.env
    environment :
      - PYTHONPATH=./bot
    logging:
      options:
        max-size: "1M"
        max-file: "10"

  serving:
    image: gcr.io/cloud-devrel-public-resources/gcloud-container-1.14.0:latest
    ports:
      - "8501:8501"
    volumes:
      - ./tf-model:/tmp/mounted_model/0001
    logging:
      options:
        max-size: "1M"
        max-file: "10"

  mongo:
    image: mongo:4.2.15
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    logging:
      options:
        max-size: "1M"
        max-file: "10"
